
kind:               Deployment
apiVersion:         apps/v1

metadata:
    name:           mi-deployment-ivan

spec:
    replicas:       3

    selector:    
        matchLabels:
            app:            web-server
    template:
        metadata:
            labels:
                app:        web-server
        spec: 
            containers:
                - name:     mi-contenedor
                  image:    bitnami/nginx
                  imagePullPolicy: IfNotPresent

---
kind:               Service
apiVersion:         v1
metadata:
  name:             servicio-web-ivan

spec:
  type:            NodePort
  ports:
    - port:        80   
      targetPort:  80   
      nodePort:    30101

  selector:
    app:          web-server
